// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"
)

type Checkin struct {
	ID         int64
	EventID    int64
	CreateTime time.Time
}

type Event struct {
	ID         int64
	Name       string
	CreateTime time.Time
}
