// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"
)

type Checkin struct {
	ID         int64     `json:"id"`
	EventID    int64     `json:"event_id"`
	CreateTime time.Time `json:"create_time"`
}

type Event struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	CreateTime time.Time `json:"create_time"`
}
