name: Build multi-arch image

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0
      - 'v*.*.*-*'  # Also matches pre-release lie v1.0.0-beta.1

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Install Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2️⃣ Log in to container registry
      # You can switch ghcr.io → docker.io if you prefer Docker Hub
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Build and push multi-arch image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/keribend/hello-web:${{ github.ref_name }}
            ghcr.io/keribend/hello-web:latest

